apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-web-deploy
  labels:
    app: ecomm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecomm
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ecomm
        tier: frontend
    spec:
      containers:
      - image: cheredia2k12/ecomm:latest
        name: ecomm
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: ecomm-mysql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: ecomm
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: ecomm-persistent-storage
          mountPath: /var/www/html

#      restartPolicy: Always
      volumes:
      - name: ecomm-persistent-storage
        persistentVolumeClaim:
          claimName: php-pv-claim
