apiVersion: v1
kind: Service
metadata:
  name: ecomm
  labels:
    app: ecomm
spec:
  ports:
    - port: 80
  selector:
    app: ecomm
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: ecomm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ecomm
  labels:
    app: ecomm
spec:
  selector:
    matchLabels:
      app: ecomm
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ecomm
        tier: frontend
    spec:
      containers:
      - image: cheredia2k12/ecomm:latest
        name: ecomm
        env:
        - name: ecomm_DB_HOST
          value: ecomm-mysql
        - name: ecomm_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: ecomm
        volumeMounts:
        - name: ecomm-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: ecomm-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
