apiVersion: v1
kind: Service
metadata:
  name: e-comme
  labels:
    app: e-comme
spec:
  ports:
    - port: 80
  selector:
    app: e-comme
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  labels:
    app: e-comme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: e-comme
  labels:
    app: e-comme
spec:
  selector:
    matchLabels:
      app: e-comme
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: e-comme
        tier: frontend
    spec:
      containers:
        - image: cheredia2k12/ecomm:latest
        name: e-comme
        env:
        - name: PHP_DB_HOST
          value: ecomm-mysql
        - name: PHP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: e-comme
        volumeMounts:
        - name: php-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: php-persistent-storage
        persistentVolumeClaim:
          claimName: php-pv-claim
