secretGenerator:
- name: mysql-pass
  literals:
  - password=Obligatorio_isc_2020
resources:
  - deployment-mysql.yaml
  - deployment-web.yaml
  - pvc-mysql.yaml
  - service-mysql.yaml
  - service-web.yaml
  - hpa.yaml
