apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-deploy
  labels:
    app: ecomm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecomm
  template:
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
      - name: php-apache
        image: cheredia2k12/ecomm:latest
        imagePullPolicy: Always
        env:
        - name: ecomm_DB_HOST
          value: ecomm-mysql
        - name: ecomm_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
#        volumeMounts:
#        - name: ecomm-persistent-storage
#          mountPath: /var/www/html
#      volumes:
#      - name: ecomm-persistent-storage
#        persistentVolumeClaim:
#          claimName: wp-pv-claim