apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: apache
spec:
  ports:
    - port: 80
  selector:
    app: apache
#    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: cheredia2k12/ecomm:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80